config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('statistics/', include('main.urls', namespace='main')),
    path('calculations/', include('statistic.urls',namespace='statistic')),
    path('crm/', include('products.urls', namespace='products')),
    path('', include('trendi.urls', namespace='trendi')),
    path("__debug__/", include("debug_toolbar.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/urls.py
from django.urls import path
from .views import OrdersView,OrderDetail, OrdersStatusView, StorageView, ExpensesView, StaffsView, PackageView,PackageDetailView

app_name = 'main'
urlpatterns = [
    path('orders/', OrdersView.as_view(), name='order_page'),
    path('orders/orders_status', OrdersStatusView.as_view(), name='orders_status'),
    path('orders/<pk>', OrderDetail.as_view(), name='order_detail'),
    path('storage/', StorageView.as_view(), name='storage'),
    path('expenses/',ExpensesView.as_view(), name='expenses'),
    path('staffs/',StaffsView.as_view(), name='staffs'),
    path('naborlar/',PackageView.as_view(), name='package_add'),
    path('naborlar/detail/<pk>', PackageDetailView.as_view(),name='package_detail')
]

products/urls.py
from django.urls import path
from . import views
from django.contrib.auth.views import LogoutView
app_name = 'products'
urlpatterns = [
    path('', views.ProductsList.as_view(), name='product_list'),
    path('products/<pk>', views.ProductDetail.as_view(), name='product_detail'),
    path('product/add_to_card/<product_id>', views.add_to_cart, name='add_to_card'),
    path('orders/', views.CustomerOrdersView.as_view(), name='customer_order_page'),
    path('orders/<pk>', views.CustomerOrderDetail.as_view(), name='cutomer_order_detail'),
    path('cart_page/', views.CardView.as_view(), name='cart'),
    path('wishlist/toggle/<int:product_id>/', views.add_to_wishlist, name='add_to_wishlist'),
    path('wishlist/', views.WishListView.as_view(),name='wishlist'),
    path('logout', LogoutView.as_view(), name='logout'),
]

trendi/urls.py
from django.urls import path
from .views import *
app_name = 'trendi'

urlpatterns = [
    path('', TrendiView.as_view(), name='trendi_main'),
    path('cart_page/', CardView.as_view(), name='cart'),
    path('mywishlist/', WishListView.as_view(), name='wishlist'),
    path('add-to-wishlist/<product_id>/', add_to_wishlist, name='wishlist_add_function'),
    path('add_to_card/<product_id>', add_to_card, name='add_to_cart')
]

products/models.py
from django.db import models
from django_resized import ResizedImageField



class Aksiyalar_qoshish(models.Model):
    name = models.CharField(max_length=200)
    description = models.TextField(blank=True, null=True)
    date_added = models.DateTimeField(auto_now_add=True)
    image = models.ImageField(upload_to="aksiyalar_rasmlari/")
    
    def __str__(self):
        return str(self.name)


class Storage(models.Model):
    name = models.CharField(max_length=250)
    last_updated = models.DateTimeField(auto_now_add=True)
    

    def overall_products_number(self):
        count = 0
        for i in self.products.all():
            count += i.amount
        return count
    


    def __str__(self):
        return self.name


class ProductCategory(models.Model):
    name = models.CharField(max_length=250)
    slug = models.SlugField(max_length=250, unique=True)


    def __str__(self):
        return str(self.name)


class ProductTag(models.Model):
    name = models.CharField(max_length=250)
    slug = models.SlugField(max_length=250, unique=True)


    def __str__(self):
        return str(self.name)


class Product(models.Model):
    name = models.CharField(max_length=250,verbose_name = "Tovar nomi")
    price = models.IntegerField(default=0,verbose_name='Narxi')
    body_price = models.IntegerField(default=0,verbose_name='Tan Narxi')
    amount = models.PositiveIntegerField(default=0,verbose_name='Soni')
    discount = models.PositiveIntegerField(default=0,verbose_name='Chegirma')
    image = ResizedImageField(size=[570,650],upload_to='movie_posters/')
    description = models.TextField(blank=True,verbose_name="Tovar haqida ma'lumot")
    category = models.ForeignKey(ProductCategory, on_delete=models.CASCADE, related_name='products')
    tag = models.ForeignKey(ProductTag, on_delete=models.CASCADE, related_name='products', blank=True, null=True)
    storage = models.ForeignKey(Storage, on_delete=models.CASCADE, related_name='products', blank=True, null=True)
    sold_amount = models.PositiveIntegerField(default=0)
   

    class Meta:
        ordering = ['id']


    def products_status_in_storage(self):
        overall_products = self.storage.overall_products_number()
        if overall_products > 0:
            percentage = (self.amount / overall_products) * 100
            return round(percentage)
        else:
            return 0


    def __str__(self):
        return str(self.name)
    

products/forms.py
from django import forms
from .models import Product

class ProductAddForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = '__all__'
        exclude = ['tag','sold_amount']
        widgets = {
            'name':forms.TextInput(attrs={'class':'form-control',}),
            'price':forms.NumberInput(attrs={'class':'form-control'}),
            'net_profit':forms.NumberInput(attrs={'class':'form-control'}),
            'body_price':forms.NumberInput(attrs={'class':'form-control'}),
            'old_price':forms.NumberInput(attrs={'class':'form-control'}),
            'amount':forms.NumberInput(attrs={'class':'form-control'}),
            'discount':forms.NumberInput(attrs={'class':'form-control'}),
            'image':forms.FileInput(attrs={'class':'form-control-file'}),
            'description':forms.TextInput(attrs={'class':'form-control'}),
            'category':forms.Select(attrs={'class':'form-control'}),
            'storage':forms.Select(attrs={'class':'form-control'}),
            # 'tag':forms.Select(attrs={'class':'form-control'}),
        }

products/views.py
from typing import Any
from django.db.models.query import QuerySet
from django.shortcuts import render, get_object_or_404, redirect
from django.views.generic import ListView, DetailView, TemplateView
from .models import Product, ProductCategory, ProductTag
from django.http import HttpResponse
from main.models import Orders, CartItems, OrderItems, WishList, Packages, PackageItems
from django.views import View
from .forms import ProductAddForm
from django.urls import reverse_lazy
from django.views.generic.edit import FormView
from django.http import JsonResponse
from django.views.decorators.http import require_POST
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth import login , authenticate
from django.urls import reverse
from django.http import HttpResponseRedirect
from django.contrib.auth.models import User
from django.contrib import messages









class ProductsList(FormView,ListView):
    model = Product
    form_class = ProductAddForm
    template_name = 'products/ecom-product-grid.html'
    paginate_by = 8
    success_url = reverse_lazy('/')

   
    def get_queryset(self):
        queryset = super().get_queryset()
        if 'billur_products' in self.request.GET:
            queryset = queryset.filter(category__name='Billur').select_related('category')
        elif 'extra_products' in self.request.GET:
            queryset = queryset.filter(category__name='Boshqalar').select_related('category')
        elif 'search' in self.request.GET:
            queryset = queryset.filter(name__icontains=self.request.GET.get('product')).select_related('category')
        return queryset



    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        wishlist = WishList.objects.get_or_create(session_key=self.request.session.session_key)
        title = None
        if 'billur_products' in self.request.path:
            title = 'Billur tovarlar'
        elif 'extra-products' in self.request.path:
            title = "Boshqalar"
        else:
            title = " "
        print(title)
        try:
            user = User.objects.get(id=self.request.user.id)
        except User.DoesNotExist:
            user = None
        # print(user)
        context.update({
            'wishlist_products':wishlist,
            'login_form': AuthenticationForm(),
            'product_form': ProductAddForm(),
            'user': user,
            'title':title,
            'naborlar':Packages.objects.all()
        })  
        return context
    

    def post(self, request, *args, **kwargs):
        self.object_list = self.get_queryset()
        if 'new_product_add' in request.POST:
            form = ProductAddForm(request.POST,request.FILES)
            if form.is_valid():
                try:
                    product = Product.objects.get(name=form.cleaned_data['name'])
                    product.name = form.cleaned_data['name']
                    product.amount = form.cleaned_data['amount']
                    product.discount = form.cleaned_data['discount']
                    product.price = form.cleaned_data['price']
                    product.image = form.cleaned_data['image']
                    product.description = form.cleaned_data['description']
                    product.category = form.cleaned_data['category']
                    product.save()
                except Product.DoesNotExist:
                    form.save()
            else:
                print(form.errors)
                print('form is not valid -----------------')
            # return self.form_invalid(form)
        if 'login' in request.POST:
            login_form = AuthenticationForm(data=request.POST)
            if login_form.is_valid():
                user = authenticate(
                    username=login_form.cleaned_data['username'],
                    password=login_form.cleaned_data['password'],
                )
                if user is not None:
                    login(request, user)
                    print('logged in')
                    return redirect('products:product_list')
                else:
                    print('wrong')
                    return redirect('products:product_list')
        if 'add_to_package' in request.POST:
            product = Product.objects.get(id=request.POST.get('product'))
            quantity = request.POST.get('quantity')
            package = Packages.objects.get(id=request.POST.get('package'))
            package_item = PackageItems.objects.create(
                product = product,
                quantity = quantity,
                package = package
            )
        return render(request, self.template_name, self.get_context_data())

    
class ProductDetail(DetailView):
    model = Product
    template_name = 'products/ecom-product-detail.html'


def add_to_cart(request, product_id):
    referring_url = request.META.get('HTTP_REFERER')
    product = get_object_or_404(Product, id=product_id)
    session_key = request.session.session_key
    if 'quantity' in request.POST:
        quantity = request.POST.get('quantity')
    

    if not session_key:
        request.session.save()
        session_key = request.session.session_key

    
    try:
        cart_item = CartItems.objects.get(session_key=session_key, product_id=product.id)
        quantity = request.POST.get('quantity')
        if quantity != None:
            if product.amount == 0 or product.amount < int(quantity):
                return HttpResponse('<h1>Omborda Mahsulot yetrali emas</h1>')

            cart_item.quantity += int(quantity)
            cart_item.save()


    except CartItems.DoesNotExist:
        quantity = request.POST.get('quantity')
        if quantity:
            quantity = int(quantity)
            CartItems.objects.create(
                product_id=product_id,
                session_key=session_key,
            )
            cart_item = CartItems.objects.get(session_key=session_key, product_id = product_id)
            cart_item.quantity += quantity
            cart_item.save()
        else:
            cart_item = CartItems.objects.create(
                product_id=product_id,
                session_key=session_key,
            )
            cart_item.quantity += 1
            cart_item.save()
    return redirect(referring_url)


class CardView(View):
    template_name ='card_page.html'

    def get_context_data(self, request,**kwargs):
        session_key = request.session.session_key
        try:
            cart_items = CartItems.objects.filter(session_key=session_key)
        except CartItems.DoesNotExist:
            return HttpResponse('<h1>Savatcha Mahsuotlari topilmadi!!! oldin Savatchaga mahsulot qo\'shing</h1>')
        kwargs['cart_items'] = cart_items
        kwargs['cart_sum'] = sum([i.overall_price() for i in cart_items])
        return kwargs

    def get(self, request, *args, **kwargs):
        return render(request, self.template_name, self.get_context_data(request))


    def post(self, request, *args, **kwargs):
        ctxt = {}

        if 'add_quantity' in request.POST:
            product = CartItems.objects.get(session_key=request.session.session_key,product_id=request.POST.get('product'))
            quantity = request.POST.get('quantity')
            products = Product.objects.get(id=product.product.id)
            if products.amount < int(quantity):
                messages.warning(request, 'Kechirasiz mahsulot yetarli emas!! Boshqa Mahsulotlarni ham qarap ko\'ring')
            else:
                product.quantity = int(quantity)
                product.save()

        elif 'delete' in request.POST:
            product = CartItems.objects.get(session_key=request.session.session_key,product_id=request.POST.get('product_delete'))
            product.delete()
            return redirect("/cart_page/")
        elif 'order' in request.POST:
            session_key = request.session.session_key
            cart_items = CartItems.objects.filter(session_key=session_key)
            order_amount = sum([i.overall_price() for i in cart_items])
            # print(cart_items)
            if order_amount > 100000:
                order_instance = Orders.objects.create(
                customer_full_name=request.POST.get('customer_full_name'),
                address=request.POST.get('address'),
                target=request.POST.get('target'),
                phone_number=request.POST.get('phone_number'),
                session_key=session_key,
                )
                print(cart_items)
                for i in cart_items:
                    print(i.product)
                    order_items = OrderItems.objects.create(
                        quantity = i.quantity,
                        sessionkey = session_key,
                        order = order_instance,
                        products = i.product
                        )
                    # print()
                cart_items.delete()
                # order_instance.items.set(cart_items)
            else: 
                messages.warning(request, 'Umumiy qiymat 100.000 so\'mni tashkil etganda buyurtma berish mumkin!!!')           
        return render(request, self.template_name, self.get_context_data(request,**ctxt))


class CustomerOrdersView(View):
    template_name = 'customers/customer_orders.html'


    def get_context_data(self, *args, **kwargs):
        return kwargs
    

    def get(self, request, *args, **kwargs):
        context = self.get_context_data()
        session_key = request.session.session_key
        context['orders'] = Orders.objects.filter(session_key=session_key)
        return render(request, self.template_name, context)
    

    def post(self, request, *args, **kwargs):
        context = {}
        return render(request, self.template_name, self.get_context_data(**context))


class CustomerOrderDetail(DetailView):
    model = Orders
    template_name = 'order_detail.html'

templates/products/ecom-product-grid.html
{% extends 'wrapper.html' %}
{% load static %}
{% block title %}Products{% endblock title %}
{% block style %}
<script src="https://code.jquery.com/jquery-3.6.4.min.js"></script>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css" />

<script>
    $(document).ready(function () {
        $('.wishlist-toggle').click(function () {
            var productId = $(this).data('product-id');

            $.ajax({
                url: 'crm/wishlist/toggle/' + productId + '/',
                type: 'POST',
                dataType: 'json',
                headers: { 'X-CSRFToken': getCookie('csrftoken') }, // Include CSRF token
                success: function (data) {
                    var wishlistToggle = $('.wishlist-toggle[data-product-id="' + productId + '"]');
					var heartIcon = wishlistToggle.find('#wishlist-icon');
                    if (data.is_added) {
                        // wishlistToggle.css('color', 'red');
						heartIcon.addClass('in_wishlist')
						console.log(heartIcon);
                    } else {
                        // wishlistToggle.css('color', 'blue');
						heartIcon.removeClass('in_wishlist')

                    }
                }
            });
        });

        function getCookie(name) {
            var cookieValue = null;
            if (document.cookie && document.cookie !== '') {
                var cookies = document.cookie.split(';');
                for (var i = 0; i < cookies.length; i++) {
                    var cookie = cookies[i].trim();
                    if (cookie.substring(0, name.length + 1) === (name + '=')) {
                        cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                        break;
                    }
                }
            }
            return cookieValue;
        }
    });
</script>
<style>
	.icon{
		color: blue;
	}
	.in_wishlist{
		color: red;
	}
</style>
{% endblock style %}
{% block content %}
{% load crispy_forms_tags %}
                <div class="page-titles" >
					{% for message in messages %}
        								<div class="alert alert-{{ message.tags }} col-10 mb-4" style="text-align:center;">
          											{{ message }}
        								</div>
        			{% endfor %}
						<div class="d-flex justify-content-between align-items-center flex-wrap">
							<h1>
								{% if 'extra_products' in request.GET %}
									Boshqalar
								{% elif 'billur_products' in request.GET %}
    								Billur Tovarlar
								{% else %}
    								<p> </p>
								{% endif %}
							</h4>
							
								<div class="d-flex justify-content-end align-items-center flex-wrap">
									<div class="nav-item mt-2 mr-4">
										<form action="" method="GET">
											<div class="input d-flex align-items-center form-control">
												<div><input type="text" name="product" style="border: none;outline: none;padding: 4% 5%;" placeholder="Izlash"></div>
												<button name="search" type="submit" style="background-color: transparent;border: none; padding: 2% 2%;"><i class="flaticon-381-search-2" style="font-size: 20px;"></i></button>
											</div>
										</form>
									</div>
									{% if user.is_staff %}
									<div class="d-none d-lg-block d-sm-block d-md-block" style="float: right;">
										<button type="button" class="btn btn-outline-secondary mt-2" name="new_product_add" data-toggle="modal" data-target="#exampleModal">Mahsulot qo'shish</button>
									</div>
									{% else %}
									<div class="d-none d-lg-block d-sm-block d-md-block" style="float: right;">
										<button type="button"  data-target="#loginModal" data-toggle="modal" class="btn btn-outline-success">Log in</button>
									</div>
									{% endif %}
								</div>
						</div>
                </div>
                <div class="row">
					{% for i in object_list %}
					<div class="col-xl-3 col-lg-6 col-md-6 col-sm-6">
                        <div class="card">
                            <div class="card-body">
                                <div class="new-arrival-product">
									<a href="{% url 'products:product_detail' i.id %}">
                                    <div class="new-arrivals-img-contnent" style="width: 100%;height: 300px;">
                                        <img class="img-fluid" src="{{ i.image.url }}" alt="" style="width: 100%;height:100%;">
                                    </div>
									</a>
                                    <div class="new-arrival-content mt-4">
                                        <div>
											<div class="d-flex justify-content-between align-items-center pr-3">
												<h4 style="font-size: 22px;color: black;">
													{{ i.name }}
													<span class="text-danger">{% if i.category.name == 'Billur' %}(Billur){% else %}{% endif %}</span>
												</h4>
												<p class="px-2 py-2 wishlist-toggle"   style="cursor: pointer;" data-product-id="{{ i.id }}" name="wishlist">
													<i id="wishlist-icon" class="fas fa-heart icon {% if i in wishlist_products.products.all %}in_wishlist{% endif %}" style="font-size: 20px;"></i>
												</p>
											</div>
											<p style="font-size: 22px;color: black;">Omborda: {% if i.amount == 0 %}mavjud emas {% else %} {{ i.amount }}ta{% endif %}</p>
										</div>
                                        <div class="mt-2" 
											style="font-weight: 600;
												color: #0B2A97;
												font-size: 24px;
												">
												{{ i.price }}so'm
										</div>
										{% if user.is_superuser %}
										<div class="mt-2 d-flex align-items-center justify-content-start" data-toggle="modal" data-target="#nabor_add_{{ i.id }}" style="cursor: pointer;">
											<p>
												<svg xmlns="http://www.w3.org/2000/svg" height="20" width="20" viewBox="0 0 640 512">
													<path d="M58.9 42.1c3-6.1 9.6-9.6 16.3-8.7L320 64 564.8 33.4c6.7-.8 13.3 2.7 16.3 8.7l41.7 83.4c9 17.9-.6 39.6-19.8 45.1L439.6 217.3c-13.9 4-28.8-1.9-36.2-14.3L320 64 236.6 203c-7.4 12.4-22.3 18.3-36.2 14.3L37.1 170.6c-19.3-5.5-28.8-27.2-19.8-45.1L58.9 42.1zM321.1 128l54.9 91.4c14.9 24.8 44.6 36.6 72.5 28.6L576 211.6v167c0 22-15 41.2-36.4 46.6l-204.1 51c-10.2 2.6-20.9 2.6-31 0l-204.1-51C79 419.7 64 400.5 64 378.5v-167L191.6 248c27.8 8 57.6-3.8 72.5-28.6L318.9 128h2.2z"/>
												</svg>
											</p>
											<h4 class="ml-2 mt-1" style="font-size: 18px;">To'plamga qo'shish</h4>
										</div>
										{% endif %}
										<div>
											<form action="{% url 'trendi:add_to_cart' i.id %}" method="POST" class="d-flex align-items-center">
												{% csrf_token %}
												<input type="number" name="quantity" class="form-control input-number mt-1" value="1" style="height: 100%;">											
												<button class="btn btn-primary-sm d-flex" type="submit">
													<i class="fa fa-shopping-basket mr-2"></i>Savatchaga
												</button>
											</form>
										</div>
										<!-- <div class="mt-4 d-flex justify-content-between align-items-center">
											<button style="cursor: pointer;" class="btn btn-outline-success counter_btn">
												<svg xmlns="http://www.w3.org/2000/svg" height="1.5em" viewBox="0 0 576 512">
													<style>svg{fill:#045ffb}</style>
													<path d="M0 24C0 10.7 10.7 0 24 0H69.5c22 0 41.5 12.8 50.6 32h411c26.3 0 45.5 25 38.6 50.4l-41 152.3c-8.5 31.4-37 53.3-69.5 53.3H170.7l5.4 28.5c2.2 11.3 12.1 19.5 23.6 19.5H488c13.3 0 24 10.7 24 24s-10.7 24-24 24H199.7c-34.6 0-64.3-24.6-70.7-58.5L77.4 54.5c-.7-3.8-4-6.5-7.9-6.5H24C10.7 48 0 37.3 0 24zM128 464a48 48 0 1 1 96 0 48 48 0 1 1 -96 0zm336-48a48 48 0 1 1 0 96 48 48 0 1 1 0-96z"/>
												</svg>
											</button>
											<div class="input-group mx-4 int_input" style="display: none;">
												<div class="input-group-prepend">
													<button class="btn btn-outline-success minusBtn">-</button>
												</div>
												<input type="number" class="form-control quantity" value="1" style="color: black;">
												<div class="input-group-append">
													<button class="btn btn-outline-success plusBtn">+</button>
												</div>
											</div>
										</div> -->
                                    </div>
									<div class="modal fade" id="nabor_add_{{ i.id }}" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
										<div class="modal-dialog" role="document">
										  <div class="modal-content">
										  <form method="POST">
											{% csrf_token %}
										  <div class="modal-header">
											<h5 class="modal-title" id="exampleModalLabel">Nabor Qo'shish</h5>
											<button type="button" class="close" data-dismiss="modal" aria-label="Close">
											<span aria-hidden="true">&times;</span>
											</button>
										  </div>
										  <div class="modal-body">
											  <input type="text" name="product" value="{{ i.id }}" class="d-none">
											<input type="number" name="quantity" class="form-control mb-2" placeholder="soni" style="color: black;">
											<select name="package" class="form-control" style="color: black;">
												<option selected >Nabor tanlang</option>
												{% for nabor in naborlar %}
												<option value="{{ nabor.id }}">{{ nabor.name }}</option>
												{% endfor %}
											</select>
										  </div>
										  <div class="modal-footer">
											<button type="submit" class="btn btn-primary" name="add_to_package">Saqlash</button>
										  </div>
										</form>
										  </div>
										</div>
									  </div>
                                </div>
                            </div>
                        </div>
                    </div>
					{% endfor %}
                </div>
            </div>
			<div class='d-flex justify-content-center align-items-center'>
				<nav>
					<ul class="pagination pagination-gutter">
						{% if current_page.has_previous %}
						<li class="page-item page-indicator">
							<a class="page-link" href="?page=1">
								<i class="la la-angle-left"></i>
							</a>
						</li>
						{% endif %}
						{% for page_number in paginator.page_range %}
						<li class="page-item {% if page_number == current_page.number %} active {% endif %}">
							<a class="page-link" href="?page={{ page_number }}">{{ page_number }}</a>
						</li>
						{% endfor %}
						{% if current_page.has_next %}
						<li class="page-item page-indicator">
							<a class="page-link" href="?page={{ paginator.num_pages }}">
								<i class="la la-angle-right"></i></a>
						</li>
						{% endif %}
					</ul>
				</nav>
			</div>
{% endblock content %}
{% block scripts %}
<!-- <script>
    $(document).ready(function () {
        $('.counter_btn').click(function () {
            // Toggle the visibility of the corresponding input group
            $(this).siblings('.int_input').toggle();
        });

        $('.plusBtn').click(function () {
            var quantity = parseInt($(this).siblings('.quantity').val());
            $(this).siblings('.quantity').val(quantity + 1);
        });

        $('.minusBtn').click(function () {
            var quantity = parseInt($(this).siblings('.quantity').val());
            if (quantity > 1) {
                $(this).siblings('.quantity').val(quantity - 1);
            }
        });
		$('.addToCartBtn').click(function () {
            var quantity = parseInt($(this).siblings('.quantity').val());

            $.ajax({
                url: 'product/add-to-cart' + productIds + '/', 
                method: 'POST',
                data: { quantity: quantity },
                success: function(response) {
                  
                    console.log('Product added to cart successfully.');
                },
                error: function(error) {
                    console.error('Error adding product to cart:', error);
                }
            });
        });
    });
</script> -->

{% endblock scripts %}