config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('statistics/', include('main.urls', namespace='main')),
    path('calculations/', include('statistic.urls',namespace='statistic')),
    path('crm/', include('products.urls', namespace='products')),
    path('', include('trendi.urls', namespace='trendi')),
    path("__debug__/", include("debug_toolbar.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/urls.py
from django.urls import path
from .views import OrdersView,OrderDetail, OrdersStatusView, StorageView, ExpensesView, StaffsView, PackageView,PackageDetailView

app_name = 'main'
urlpatterns = [
    path('orders/', OrdersView.as_view(), name='order_page'),
    path('orders/orders_status', OrdersStatusView.as_view(), name='orders_status'),
    path('orders/<pk>', OrderDetail.as_view(), name='order_detail'),
    path('storage/', StorageView.as_view(), name='storage'),
    path('expenses/',ExpensesView.as_view(), name='expenses'),
    path('staffs/',StaffsView.as_view(), name='staffs'),
    path('naborlar/',PackageView.as_view(), name='package_add'),
    path('naborlar/detail/<pk>', PackageDetailView.as_view(),name='package_detail')
]

products/urls.py
from django.urls import path
from . import views
from django.contrib.auth.views import LogoutView
app_name = 'products'
urlpatterns = [
    path('', views.ProductsList.as_view(), name='product_list'),
    path('products/<pk>', views.ProductDetail.as_view(), name='product_detail'),
    path('product/add_to_card/<product_id>', views.add_to_cart, name='add_to_card'),
    path('orders/', views.CustomerOrdersView.as_view(), name='customer_order_page'),
    path('orders/<pk>', views.CustomerOrderDetail.as_view(), name='cutomer_order_detail'),
    path('cart_page/', views.CardView.as_view(), name='cart'),
    path('wishlist/toggle/<int:product_id>/', views.add_to_wishlist, name='add_to_wishlist'),
    path('wishlist/', views.WishListView.as_view(),name='wishlist'),
    path('logout', LogoutView.as_view(), name='logout'),
]

templates/customers/customer_order_detail.html
{% extends 'wrapper.html' %}
{% load static %}
{% block style %}
<link rel="icon" type="image/png" sizes="16x16" href="./images/favicon.png">
<link rel="stylesheet" href="./vendor/chartist/css/chartist.min.css">
<link href="./vendor/owl-carousel/owl.carousel.css" rel="stylesheet">
{% endblock style %}
{% block title %}Mening Zakazlarim{% endblock title%}
{% block content %}
              <div class="row d-flex justify-content-center align-items-center h-100">
                <div class="col-10">
                  {% for i in object.items.all %}
                  <div class="card rounded-3 mb-4 mt-4">
                    <div class="card-body p-4">
                      <div class="row d-flex justify-content-between align-items-center pr-8">
                        <div class="col-md-2 col-lg-2 col-xl-2" style="height: 200px;">
                          <img src="{{ i.product.image.url }}" class="img-fluid rounded-3" alt="{{ i.product.name }}" style="width: 100%;height: 100%;">
                        </div>
                        <div class="col-md-3 col-lg-3 col-xl-3">
                          <p class="lead fw-normal mb-2">{{ i.product.name }}</p>
                          <p><span class="text-muted">Chegirma: </span>{{ i.product.discount }}%</p>
                          <p><span class="text-muted">Donasi: </span>{{ i.product.price }} so'm</p>
                        </div>
                        <div class="col-md-3 col-lg-3 col-xl-2 d-flex">
                            <h4>{{ i.quantity }}ta</h4>
                          <!-- <form action="" method="POST" class="d-flex">
                            {% csrf_token %}
                            <input type="text" name="product" value="{{ i.product.id }}" style="display: none;">
                            <input id="form1" min="0" name="quantity" value="{{ i.quantity }}" type="number" class="form-control form-control-sm my-2 mx-2" />
                            <button class="btn btn-link btn-success text-light  px-2  my-2 mx-2" name="add_quantity">save</button>
                          </form> -->
                        </div>
                        <div class="col-md-3 col-lg-2 col-xl-2 offset-lg-1">
                          <h5 class="mb-0">{{ i.overall_price }} so'm</h5>
                        </div>
                        <div class="col-md-1 col-lg-1 col-xl-1 text-end pr-5">
                          <form action="" method="POST" class="d-flex justify-content-center align-items-center">
                            {% csrf_token %}
                            <input type="number" name="product_delete" value="{{ i.id }}" style="display: none;">
                            <button type="submit" name="delete"  style="border: none;background-color: transparent;">
                              <svg xmlns="http://www.w3.org/2000/svg" height="2em" viewBox="0 0 448 512">
                                <style>svg{fill:#808185}</style>
                                <path d="M135.2 17.7L128 32H32C14.3 32 0 46.3 0 64S14.3 96 32 96H416c17.7 0 32-14.3 32-32s-14.3-32-32-32H320l-7.2-14.3C307.4 6.8 296.3 0 284.2 0H163.8c-12.1 0-23.2 6.8-28.6 17.7zM416 128H32L53.2 467c1.6 25.3 22.6 45 47.9 45H346.9c25.3 0 46.3-19.7 47.9-45L416 128z"/>
                              </svg>
                            <button>
                          </form>
                        </div>
                      </div>
                    </div>
                  </div>
                  {% endfor %}
                </div>
              </div>

{% endblock content %}

templates/customers/customer_orders.html
{% extends 'wrapper.html' %}
{% load static %}
{% block title %}Zakazlar{% endblock title %}
{% block content %}
                <div class="row">
                    <div class="col-lg-12">
                        <div class="card">
                            <div class="card-body">
                                <div class="table-responsive">
                                    <table class="table table-sm mb-0 table-responsive-lg text-black">
                                        <thead>
                                            <tr>
                                                <th class="align-middle">
                                                    <div class="custom-control custom-checkbox ml-1">
														<input type="checkbox" class="custom-control-input" id="checkAll">
														<label class="custom-control-label" for="checkAll"></label>
													</div>
                                                </th>
                                                <th class="align-middle">Buyurtma</th>
                                                <th class="align-middle pr-7">Sana</th>
                                                <th class="align-middle minw200">Adress</th>
                                                <th class="align-middle text-right">Mo'ljal</th>
                                                <th class="align-middle text-right">Amount</th>
                                                <th class="no-sort"></th>
                                            </tr>
                                        </thead>
                                        <tbody id="orders">
											{% for i in orders %}
                                            <tr class="btn-reveal-trigger">
                                                <td class="py-2">
                                                    <div class="custom-control custom-checkbox checkbox-success">
														<input type="checkbox" class="custom-control-input" id="checkbox">
														<label class="custom-control-label" for="checkbox"></label>
													</div>
                                                </td>
                                                <td class="py-2">
                                                    <a  href="{% url 'products:cutomer_order_detail' i.id %}">
                                                        <strong>#{{ i.id }}</strong></a> by <strong>{{ i.customer_full_name }}</strong><br /><a href="mailto:ricky@example.com">{{ i.phone_number }}</a></td>
                                                <td class="py-2">{{ i.date_added }}</td>
                                                <td class="py-2">{{ i.address }}</td>
                                                <td class="py-2">{{ i.target }}</td>
                                                <td class="py-2 text-right"><span class="badge badge-success">{{ i.status }}<span
                                                            class="ml-1 fa fa-check"></span></span>
                                                </td>
                                                <td class="py-2 text-right">{{ i.get_overall }}so'm
                                                </td>
                                            </tr>
                                           	{% endfor %}
                                        </tbody>
                                    </table>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
{% endblock content %}
           