config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('statistics/', include('main.urls', namespace='main')),
    path('calculations/', include('statistic.urls',namespace='statistic')),
    path('crm/', include('products.urls', namespace='products')),
    path('', include('trendi.urls', namespace='trendi')),
    path("__debug__/", include("debug_toolbar.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/urls.py
from django.urls import path
from .views import OrdersView,OrderDetail, OrdersStatusView, StorageView, ExpensesView, StaffsView, PackageView,PackageDetailView

app_name = 'main'
urlpatterns = [
    path('orders/', OrdersView.as_view(), name='order_page'),
    path('orders/orders_status', OrdersStatusView.as_view(), name='orders_status'),
    path('orders/<pk>', OrderDetail.as_view(), name='order_detail'),
    path('storage/', StorageView.as_view(), name='storage'),
    path('expenses/',ExpensesView.as_view(), name='expenses'),
    path('staffs/',StaffsView.as_view(), name='staffs'),
    path('naborlar/',PackageView.as_view(), name='package_add'),
    path('naborlar/detail/<pk>', PackageDetailView.as_view(),name='package_detail')
]

trendi/urls.py
from django.urls import path
from .views import *
app_name = 'trendi'

urlpatterns = [
    path('', TrendiView.as_view(), name='trendi_main'),
    path('cart_page/', CardView.as_view(), name='cart'),
    path('mywishlist/', WishListView.as_view(), name='wishlist'),
    path('add-to-wishlist/<product_id>/', add_to_wishlist, name='wishlist_add_function'),
    path('add_to_card/<product_id>', add_to_card, name='add_to_cart')
]

trendi/models.py
from django.db import models

# Create your models here.

trendi/views.py
from typing import Any
from django.db.models.query import QuerySet
from django.shortcuts import render, get_object_or_404, redirect
from django.views.generic import ListView, DetailView, TemplateView
from products.models import Product, ProductCategory, ProductTag, Aksiyalar_qoshish
from django.http import HttpResponse
from main.models import Orders, CartItems, OrderItems, WishList, Packages, PackageItems
from django.views import View
from django.urls import reverse_lazy
from django.views.generic.edit import FormView
from django.http import JsonResponse
from django.views.decorators.http import require_POST
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth import login , authenticate
from django.urls import reverse
from django.http import HttpResponseRedirect
from django.contrib.auth.models import User
from django.contrib import messages
from django.shortcuts import get_object_or_404
from django.http import JsonResponse
from django.views.decorators.http import require_POST
from products.views import add_to_cart
from django.db.models import Prefetch
from django.contrib import messages
# class TrendiView(TemplateView):
#     template_name = "trendi.html"

class TrendiView(ListView):
    model = Product
    template_name = "trendi.html"
    paginate_by = 6
    success_url = reverse_lazy('/')

    def get_queryset(self):
        queryset = super().get_queryset().select_related('category')
        if 'billur_products' in self.request.GET:
            queryset = queryset.filter(category__name='Billur')
        elif 'extra_products' in self.request.GET:
            queryset = queryset.filter(category__name='Boshqalar')
        elif 'filter' in self.request.GET:
            filter_object = self.request.GET.get("object")
            filter_by = self.request.GET.get("filter_by")
            if filter_by == "Eng ko'p sotilgan tovarlar":
                queryset = queryset.order_by("-sold_amount")
            else:
                queryset = queryset.filter(tag__id=int(filter_by))
        return queryset

    def get_context_data(self,**kwargs):
        session_key = self.request.session.session_key
        wishlist = WishList.objects.get_or_create(session_key=session_key)
        if 'billur_products' in self.request.GET:
            title = 'Billur tovarlar'
        elif 'extra_products' in self.request.GET:
            title = "Boshqalar"
        else:
            title = " "
        print(title)
        try:
            cart_items = CartItems.objects.filter(session_key=session_key).select_related('product__category')
        except CartItems.DoesNotExist:
            return HttpResponse('<h1>Savatcha Mahsuotlari topilmadi!!! oldin Savatchaga mahsulot qo\'shing</h1>')
        try:
            user = User.objects.get(id=self.request.user.id)
        except User.DoesNotExist:
            user = None
        context = super().get_context_data(**kwargs)
        context.update({
            'user': user,
            'cart_items_number':len(cart_items),
            'title':title,
            'wishlist':wishlist,
            "tags": ProductTag.objects.all().prefetch_related("products"),
            'aksiya': Aksiyalar_qoshish.objects.last()
        })
        return context
    def post(self, request, *args, **kwargs):
        self.object_list = self.get_queryset()
        if request.is_ajax() and 'product_id' in request.POST:
            product_id = request.POST['product_id']
            product = get_object_or_404(Product, id=product_id)
            wishlist, created = WishList.objects.get_or_create(session_key=request.session.session_key)
            wishlist.add_product(product)
            return JsonResponse({'success': True})
        return render(request, self.template_name, self.get_context_data())


class CardView(View):
    template_name ='products/client-cart.html'
    def get_context_data(self, request,**kwargs):
        referring_url = request.META.get('HTTP_REFERER')
        session_key = request.session.session_key
        
        try:
            cart_items = CartItems.objects.filter(session_key=session_key).select_related('product__category')
        except CartItems.DoesNotExist:
            messages.warning(request,"Mahsulot topilmadi...")
            return redirect(referring_url)
        kwargs['cart_items'] = cart_items
        kwargs['cart_items_number'] = len(cart_items)
        kwargs['cart_sum'] = sum([i.overall_price() for i in cart_items])
        return kwargs

    def get(self, request, *args, **kwargs):
        return render(request, self.template_name, self.get_context_data(request))


    def post(self, request, *args, **kwargs):
        ctxt = {}

        if 'add_quantity' in request.POST:
            product = CartItems.objects.get(session_key=request.session.session_key,product_id=request.POST.get('product'))
            quantity = request.POST.get('quantity')
            products = Product.objects.get(id=product.product.id)
            if products.amount < int(quantity):
                messages.warning(request, 'Kechirasiz mahsulot yetarli emas!! Boshqa Mahsulotlarni ham qarap ko\'ring')
            else:
                product.quantity = int(quantity)
                product.save()

        elif 'delete' in request.POST:
            product = CartItems.objects.get(session_key=request.session.session_key,product_id=request.POST.get('product_delete'))
            product.delete()
        elif 'order' in request.POST:
            session_key = request.session.session_key
            cart_items = CartItems.objects.filter(session_key=session_key).select_related('product')
            order_amount = sum([i.overall_price() for i in cart_items])
            # print(cart_items)
            if order_amount > 100000:
                order_instance = Orders.objects.create(
                customer_full_name=request.POST.get('customer_full_name'),
                address=request.POST.get('address'),
                target=request.POST.get('target'),
                phone_number=request.POST.get('phone_number'),
                session_key=session_key,
                )
                print(cart_items)
                for i in cart_items:
                    print(i.product)
                    order_items = OrderItems.objects.create(
                        quantity = i.quantity,
                        sessionkey = session_key,
                        order = order_instance,
                        products = i.product
                        )
                    # print()
                cart_items.delete()
                messages.warning(request,"Buyurtmangiz qabul qilindi")
            else: 
                messages.warning(request, 'Umumiy qiymat 100.000 so\'mni tashkil etganda buyurtma berish mumkin!!!')           
        return render(request, self.template_name, self.get_context_data(request,**ctxt))


class WishListView(View):
    template_name = 'trendi-wishlist.html'
    

    def get_context_data(self, **kwargs):
        session_key = self.request.session.session_key
        print(self.request.session.session_key)
        wishlist = WishList.objects.get(session_key=session_key)
        products = wishlist.products.select_related('category').all()
        status = False
        if products:
            status = True
        else:
            pass
        kwargs['wishlist'] = wishlist
        kwargs['wishlist_status'] = status
        return kwargs


    def get(self,reqeust, *args, **kwargs):
        return render(reqeust, self.template_name, self.get_context_data())
    

    def post(self,request, *args, **kwargs):
        ctxt = {}
        if 'add_to_cart' in request.POST:
            request = request
            product_id = request.POST.get('product')
            print(product_id)
            add_to_cart(request,product_id)
        elif 'delete' in request.POST:
            wishlist = WishList.objects.get(session_key=request.session.session_key)
            product_id = request.POST.get('product')
            print(product_id)
            product = get_object_or_404(Product, id=product_id)
            wishlist.products.remove(product)
        return render(request, self.template_name, self.get_context_data(**ctxt))

@require_POST
def add_to_wishlist(request, product_id):
    product = get_object_or_404(Product, id=product_id)
    session_key = request.session.session_key

    if not session_key:
        request.session.save()
        session_key = request.session.session_key

    wishlist, created = WishList.objects.get_or_create(session_key=session_key)
    
    if product in wishlist.products.all():
        wishlist.products.remove(product)
        is_added = False
    else:
        wishlist.products.add(product)
        is_added = True

    return JsonResponse({'is_added': is_added})


def add_to_card(request, product_id):
    referring_url = request.META.get('HTTP_REFERER')
    product = get_object_or_404(Product, id=product_id)
    session_key = request.session.session_key
    if 'quantity' in request.POST:
        quantity = request.POST.get('quantity')
    

    if not session_key:
        request.session.save()
        session_key = request.session.session_key

    
    try:
        cart_item = CartItems.objects.get(session_key=session_key, product_id=product.id)
        quantity = request.POST.get('quantity')
        if quantity != None:
            if product.amount == 0 or product.amount < int(quantity):
               messages.warning(request, f"Mahsulot omborda yetarli emas!!!")
               
            messages.warning(request, f"Mahsulot omborga qo'shildi!!!")
            cart_item.quantity += int(quantity)
            cart_item.save()
            
    except CartItems.DoesNotExist:
        quantity = request.POST.get('quantity')
        if quantity:
            quantity = int(quantity)
            CartItems.objects.create(
                product_id=product_id,
                session_key=session_key,
            )

templates/index.html
{% extends 'wrapper.html' %}
{% load static %}
{% block title %}Statistikalar{% endblock title %}
{% block content %}
{% load crispy_forms_tags %}
<script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
<div class="row">
	<div class="col-xl-12 col-xxl-12">
		<div class="mb-4 d-flex justify-content-end">
			<button type="button" class="btn btn-outline-warning mx-2" data-toggle="modal" data-target="#exampleModal">Harajat qo'shish</button>
			<button type="button" class="btn btn-outline-warning mx-2" data-toggle="modal" data-target="#add_seller">Sotuvchi Qo'shish</button>
		</div>
		<div class="row">
			<div class="col-lg-6 col-sm-6">
				<div class="card">
					<div class="card-header">
						<h4>Shu oydagi savdo</h4>
					</div>
					<div class="card-body">
						<h2>{{ current_month_sale }} so'm<h2>
					</div>
				</div>
			</div>
			
			<div class="col-lg-6 col-sm-6">
				<div class="card">
					<div class="card-header">
						<h4>Eng ko'p savdo qilgan Sotuvchi</h4>
					</div>
					<div class="card-body">
						<h2>{{ admin_best }}</h2>
					</div>
				</div>
			</div>
			<div class="col-lg-6 col-sm-6">
				<div class="card">
					<div class="card-header">
						<h4>shu oydagi chiqim</h4>
					</div>
					<div class="card-body">
						<h2>{{ current_month_expense }} so'm<h2></h2>
					</div>
				</div>
			</div>
			<div class="col-lg-6 col-sm-6">
				<div class="card">
					<div class="card-header">
						<h4>Eng ko'p Sotilgan tovar</h4>
					</div>
					<div class="card-body">
						{% if most_sold_current_month %}
						<p style="font-size: 20px;color: black;"><h2>{{ most_sold_current_month.order_items__products__name }}</h2></p>
						<p style="font-size: 20px;color: black;">Miqdori: {{ most_sold_current_month.total_quantity }}</p>
					{% else %}
						<p>No data available for the most sold product.</p>
					{% endif %}
					</div>
				</div>
			</div>
			<div class="col-lg-6 col-sm-6">
				<div class="card">
					<div class="card-header">
						<h4>Plastik Savdo</h4>
					</div>
					<div class="card-body">
						<h2>{{card_sale.total_quantity }} so'm<h2></h2>
					</div>
				</div>
			</div>
			<div class="col-lg-6 col-sm-6">
				<div class="card">
					<div class="card-header">
						<h4>Naxd Savdo</h4>
					</div>
					<div class="card-body">
						{% if money_sale %}
						<h2>{{ money_sale.total_quantity }} so'm<h2>
						{% else %}
						<h2>Ma'lumot mavjud emas</h2>
						{% endif %}
					</div>
				</div>
			</div>
		</div>
		<div class="row">
				<div class="col-lg-6 col-sm-6">
					<div class="card">
						<div class="card-header">
							<h5 class="card-title">Sotilgan tovarlar oylik summalari</h5>
						</div>
						<div class="card-body">
							<canvas id="monthlyChart"></canvas>
						</div>
					</div>
				</div>
				<div class="col-lg-6 col-sm-6">
					<div class="card">
						<a href="{% url 'main:expenses' %}">
							<div class="card-header">
								<h4 class="card-title">Chiqimlar</h4>
							</div>
						</a>
						<div class="card-body">
							<canvas id="expenses"></canvas>
						</div>
					</div>
				</div>
				<div class="col-lg-12 col-sm-6">
					<div class="card">
						<div class="card-header">
							<h4 class="card-title">Sotuvchilar Reytingi</h4>
						</div>
						<div class="card-body">
							<canvas id="workersChart"></canvas>
						</div>
					</div>
				</div>
				
			</div>
			<div class="col-lg-12 col-sm-6">
				<div class="card">
					<div class="card-header"><h4>Sotuvchilar</h4></div>
					<div class="card-body">
						<div class="card-body">
							<div class="table-responsive">
								<table class="table header-border table-hover verticle-middle">
									<thead>
										<tr>
											<th scope="col">ID</th>
											<th scope="col">Ism Sharifi</th>
											<th scope="col">Telefon</th>
										</tr>
									</thead>
									<tbody>
										{% for i in users %}
										{% if i.is_staff == True %}
										<tr>
											<th>{{ i.id }}</th>
											<td>
												{{ i.username }}
											</td>
											<td>{{ i.phone_number }}</td>
										</tr>
										{% endif %}
										{% endfor %}
									</tbody>
								</table>
							</div>
						</div>
					</div>
				</div>
			</div>
	</div>
	


</div>
<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
	<div class="modal-dialog" role="document">
	  <div class="modal-content">
	  <form method="POST">
		{% csrf_token %}
	  <div class="modal-header">
		<h5 class="modal-title" id="exampleModalLabel">Chiqim Qo'shish</h5>
		<button type="button" class="close" data-dismiss="modal" aria-label="Close">
		<span aria-hidden="true">&times;</span>
		</button>
	  </div>
	  <div class="modal-body">
		{{ expensesForm }}
	  </div>
	  <div class="modal-footer">
		<button type="submit" class="btn btn-primary" name="add_expense">Buyurtma berish</button>
	  </div>
	</form>
	  </div>
	</div>
</div>
<div class="modal fade" id="add_seller" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
	<div class="modal-dialog" role="document">
	  <div class="modal-content">
	  <form method="POST">
		{% csrf_token %}
	  <div class="modal-header">
		<h5 class="modal-title" id="exampleModalLabel">Sotuvchi Qo'shish</h5>
		<button type="button" class="close" data-dismiss="modal" aria-label="Close">
		<span aria-hidden="true">&times;</span>
		</button>
	  </div>
	  <div class="modal-body">
			{{ sellerForm|crispy }}
	  </div>
	  <div class="modal-footer">
		<button type="submit" class="btn btn-primary" name="add_seller">Qo'shish</button>
	  </div>
	</form>
	  </div>
	</div>
</div>
{% endblock content %}
{% block scripts %}
<script>
	// JavaScript code to render the chart using the data passed from the view
	var ctx = document.getElementById('monthlyChart').getContext('2d');
	var data = JSON.parse('{{ data|safe }}');
	var labels = data.map(function(item) {
		return item.month;
	});
	console.log(data);
	var quantities = data.map(function(item) {
		return item.total_quantity;
	});

	var chart = new Chart(ctx, {
		type: 'bar',
		data: {
			labels: labels,
			datasets: [{
				label: "Oy bo'yicha",
				backgroundColor: 'rgba(75, 192, 192, 0.2)',
				borderColor: 'rgba(75, 192, 192, 1)',
				borderWidth: 1,
				data: quantities,
			}]
		},
		options: {
            responsive: true,
            maintainAspectRatio: false,
        }
	});
</script>
<script>
	// JavaScript code to render the chart using the data passed from the view
	var ctx = document.getElementById('expenses').getContext('2d');
	var data = JSON.parse('{{ expenses|safe }}');

	var labels = data.map(function(item) {
		return item.month;
	});

	var quantities = data.map(function(item) {
		return item.total_amount;
	});

	var chart = new Chart(ctx, {
		type: 'line',
		data: {
			labels: labels,
			datasets: [{
				label: "Oy bo'yicha",
				backgroundColor: 'rgba(75, 192, 192, 0.2)',
				borderColor: 'rgba(75, 192, 192, 1)',
				borderWidth: 1,
				data: quantities,
			}]
		},
		options: {
            responsive: true,
            maintainAspectRatio: false,
        }
	});
</script>
<script>
    var ctx = document.getElementById('workersChart').getContext('2d');
    var data = JSON.parse('{{ workers|safe }}');

    var labels = Array.from(new Set(data.map(item => item.month))); 
    var sellers = Array.from(new Set(data.map(item => item.seller))); 
    console.log(sellers);

    var datasets = sellers.map(seller => {
        return {
            label:  seller,
            data: labels.map(month => {
                var entry = data.find(item => item.month === month && item.seller === seller);
                return entry ? entry.total_quantity : 0;
            }),
            backgroundColor: getRandomColor(),
        };
    });

    function getRandomColor() {
        var letters = '0123456789ABCDEF';
        var color = '#';
        for (var i = 0; i < 6; i++) {
            color += letters[Math.floor(Math.random() * 16)];
        }
        return color;
    }

    var chart = new Chart(ctx, {
        type: 'bar',
        data: {
            labels: labels,
            datasets: datasets,
        },
        options: {
            responsive: true,
            maintainAspectRatio: false,
        }
    });
</script>
{% endblock scripts %}

templates/trendi_base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock title %}</title>
    <link rel="stylesheet" href="{% static 'css/treni_style.css' %}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css" integrity="sha512-iecdLmaskl7CVkqkXNQ/ZH/XLlvWZOJyj7Yy7tcenmpD1ypASozpmT/E0iPtmFIB46ZmdtAc9eNBvH0H/ZpiBw==" crossorigin="anonymous" referrerpolicy="no-referrer"/>
    
    {% block style %}{% endblock style %}
</head>
<body>
    <header>
        <div class="container">
            <div class="header-in">
                <a class="" href="/" style="width:90px;height: 70px;">
                    <img class="" src="{% static 'images/logo_billur.png' %}" alt="Site logo" style="width: 100%;height: 100%;">
                </a>
                <div class="cart d-none d-sm-block d-md-block">
                    <a href="{% url 'trendi:wishlist' %}" class="mr-2">
                        <svg width="30" height="30" viewBox="0 0 24 24" fill="white" xmlns="http://www.w3.org/2000/svg">
                            <path fill-rule="evenodd" clip-rule="evenodd" d="M11.9932 5.13581C9.9938 2.7984 6.65975 2.16964 4.15469 4.31001C1.64964 6.45038 1.29697 10.029 3.2642 12.5604C4.89982 14.6651 9.84977 19.1041 11.4721 20.5408C11.6536 20.7016 11.7444 20.7819 11.8502 20.8135C11.9426 20.8411 12.0437 20.8411 12.1361 20.8135C12.2419 20.7819 12.3327 20.7016 12.5142 20.5408C14.1365 19.1041 19.0865 14.6651 20.7221 12.5604C22.6893 10.029 22.3797 6.42787 19.8316 4.31001C17.2835 2.19216 13.9925 2.7984 11.9932 5.13581Z" stroke="black" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"/>
                        </svg>
                    </a>
                    <a href="{% url 'trendi:cart' %}">
                        <svg width="30" height="30" viewBox="0 0 24 24" fill="white" xmlns="http://www.w3.org/2000/svg">
                            <path d="M2 2H3.30616C3.55218 2 3.67519 2 3.77418 2.04524C3.86142 2.08511 3.93535 2.14922 3.98715 2.22995C4.04593 2.32154 4.06333 2.44332 4.09812 2.68686L4.57143 6M4.57143 6L5.62332 13.7314C5.75681 14.7125 5.82355 15.2031 6.0581 15.5723C6.26478 15.8977 6.56108 16.1564 6.91135 16.3174C7.30886 16.5 7.80394 16.5 8.79411 16.5H17.352C18.2945 16.5 18.7658 16.5 19.151 16.3304C19.4905 16.1809 19.7818 15.9398 19.9923 15.6342C20.2309 15.2876 20.3191 14.8247 20.4955 13.8988L21.8191 6.94969C21.8812 6.62381 21.9122 6.46087 21.8672 6.3335C21.8278 6.22177 21.7499 6.12768 21.6475 6.06802C21.5308 6 21.365 6 21.0332 6H4.57143ZM10 21C10 21.5523 9.55228 22 9 22C8.44772 22 8 21.5523 8 21C8 20.4477 8.44772 20 9 20C9.55228 20 10 20.4477 10 21ZM18 21C18 21.5523 17.5523 22 17 22C16.4477 22 16 21.5523 16 21C16 20.4477 16.4477 20 17 20C17.5523 20 18 20.4477 18 21Z" stroke="black" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"/>
                        </svg>
                        <span style="position:relative;top:-25px;color:red;">+ {{ cart_items_number }}</span>
                    </a>
                </div>
                <div class="header__burger">
                    <svg width="30" height="30" viewBox="0 0 24 24" fill="white" xmlns="http://www.w3.org/2000/svg">
                        <path d="M3 12H21M3 6H21M3 18H21" stroke="black" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"/>
                    </svg>                        
                </div>
            </div>
        </div>
    </header>
    <div class="sidebar">
        <style>
            .menu-item:hover{
                background-color: rgb(208, 204, 204);
            }
        </style>
        <div class="w-100 container">
            <a href="{% url 'trendi:cart' %}" class="menu-item d-flex justify-content-start py-1">
                <span class="mr-2">
                    <svg width="25" height="25" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
                        <path d="M2 2H3.30616C3.55218 2 3.67519 2 3.77418 2.04524C3.86142 2.08511 3.93535 2.14922 3.98715 2.22995C4.04593 2.32154 4.06333 2.44332 4.09812 2.68686L4.57143 6M4.57143 6L5.62332 13.7314C5.75681 14.7125 5.82355 15.2031 6.0581 15.5723C6.26478 15.8977 6.56108 16.1564 6.91135 16.3174C7.30886 16.5 7.80394 16.5 8.79411 16.5H17.352C18.2945 16.5 18.7658 16.5 19.151 16.3304C19.4905 16.1809 19.7818 15.9398 19.9923 15.6342C20.2309 15.2876 20.3191 14.8247 20.4955 13.8988L21.8191 6.94969C21.8812 6.62381 21.9122 6.46087 21.8672 6.3335C21.8278 6.22177 21.7499 6.12768 21.6475 6.06802C21.5308 6 21.365 6 21.0332 6H4.57143ZM10 21C10 21.5523 9.55228 22 9 22C8.44772 22 8 21.5523 8 21C8 20.4477 8.44772 20 9 20C9.55228 20 10 20.4477 10 21ZM18 21C18 21.5523 17.5523 22 17 22C16.4477 22 16 21.5523 16 21C16 20.4477 16.4477 20 17 20C17.5523 20 18 20.4477 18 21Z" stroke="black" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"/>
                    </svg>
                </span>
                <div class="mr-2" style="color:black;">
                    Savatcha
                </div>
                {% comment %} <span style="color:red;">+ {{ cart_itmes }}</span> {% endcomment %}
            </a>
            <div class="menu-item d-flex justify-content-start px-1 py-1">
                <a href="{% url 'trendi:wishlist' %}" class="mr-2">
                    <svg xmlns="http://www.w3.org/2000/svg" height="25" width="25" viewBox="0 0 512 512">
                        <path d="M225.8 468.2l-2.5-2.3L48.1 303.2C17.4 274.7 0 234.7 0 192.8v-3.3c0-70.4 50-130.8 119.2-144C158.6 37.9 198.9 47 231 69.6c9 6.4 17.4 13.8 25 22.3c4.2-4.8 8.7-9.2 13.5-13.3c3.7-3.2 7.5-6.2 11.5-9c0 0 0 0 0 0C313.1 47 353.4 37.9 392.8 45.4C462 58.6 512 119.1 512 189.5v3.3c0 41.9-17.4 81.9-48.1 110.4L288.7 465.9l-2.5 2.3c-8.2 7.6-19 11.9-30.2 11.9s-22-4.2-30.2-11.9zM239.1 145c-.4-.3-.7-.7-1-1.1l-17.8-20c0 0-.1-.1-.1-.1c0 0 0 0 0 0c-23.1-25.9-58-37.7-92-31.2C81.6 101.5 48 142.1 48 189.5v3.3c0 28.5 11.9 55.8 32.8 75.2L256 430.7 431.2 268c20.9-19.4 32.8-46.7 32.8-75.2v-3.3c0-47.3-33.6-88-80.1-96.9c-34-6.5-69 5.4-92 31.2c0 0 0 0-.1 .1s0 0-.1 .1l-17.8 20c-.3 .4-.7 .7-1 1.1c-4.5 4.5-10.6 7-16.9 7s-12.4-2.5-16.9-7z"/>
                    </svg>
                </a>
                <div>
                 Yoqtirganlarim
                </div>
             </div>
        </div>
    </div>
    <main>    
        {% block content %} {% endblock content %}
    </main>
    <script src="{% static 'js/trendi_app.js' %}"></script>
</body>
</html>